# Default values for sm-connector.
#
# Use this file to configure your app or use a second config file:
# helm upgrade release-name . --install --values values.yaml --values values.customer.yaml
# After install test the app with:
# helm test release-name

config:
  Api:
    EnableDetailedErrorMessages: false
    EnableSwagger: false

volume:
  storageClassName: manual
  capacity: 1Gi
  # Windows Docker Desktop Kubernetes (1.28.2):
  # C:\sm-connector-data -> /run/desktop/mnt/host/c/sm-connector-data
  hostPath: /run/desktop/mnt/host/c/sm-connector-data

image:
  repository: sm-connector
  pullPolicy: IfNotPresent
  tag: "" # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sm-connector.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: false # we need root to configure the Persistent Volume (PV)
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true # Our app runs as non-root user "app" (ID: 1654)
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
