name: sm-connector-to-teams

services: # https://docs.docker.com/compose/compose-file/05-services/
  init-app: # We allocate a directory and change the owner to "app" as a template for the actual volume mount.
    image: busybox:1.36.1-musl
    command:
      - sh
      - -c
      - mkdir -p /app/data
      - chown -R 1654:1654 /app/data
  app:
    image: "sm-connector-to-teams:${ImageTag}"
    ports:
      - "${PublicPort}:8080"
    volumes:
      - app-data:/app/data
    healthcheck: # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
      test: [ "CMD", "dotnet", "/app/SMConnectorToTeams.dll", "--healthcheck", "http://localhost/healthcheck" ]
      interval: 1m # Takes 1 minute for the first check, and then every minute
      timeout: 1m
    environment:
      - Api:EnableDetailedErrorMessages=${Api_EnableDetailedErrorMessages}
      - Api:EnableSwagger=${Api_EnableSwagger}

volumes: # https://docs.docker.com/compose/compose-file/07-volumes/
  app-data:
    driver: local # Use the Docker Desktop default https://docs.docker.com/compose/compose-file/07-volumes/#driver
    # Inspect data here (Docker Desktop Windows):
    # \\wsl$\docker-desktop-data\data\docker\volumes\sm-connector-to-teams_app-data\_data
