apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sm-connector-to-teams.fullname" . }}
  labels:
    {{- include "sm-connector-to-teams.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sm-connector-to-teams.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sm-connector-to-teams.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sm-connector-to-teams.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "sm-connector-to-teams.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "sm-connector-to-teams.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/data"
              name: {{ include "sm-connector-to-teams.fullname" . }}
          livenessProbe:
            httpGet:
              path: /livenesscheck
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 60
          env:
            - name: Api__EnableDetailedErrorMessages
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sm-connector-to-teams.fullname" . }}
                  key: Api.EnableDetailedErrorMessages
            - name: Api__EnableSwagger
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sm-connector-to-teams.fullname" . }}
                  key: Api.EnableSwagger
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
