# Create a persistent volume claim (PVC) that exposes the PV to a pod
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sm-connector.fullname" . }}
  labels:
    {{- include "sm-connector.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node. For single pod access, please see ReadWriteOncePod.
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}